### PR TITLE
Guild information

### PR DESCRIPTION
**Pull request by n1tr0-5urf3r**
Command to get general information about your guild 
Requires a guild ID String as parameter (maybe add it to the json in future?)
PS: Membership in the guild is required.

(Nevermind those "Added getIconURL" commits, i reversed them all, and sorry for pushing directly to master)

### CODE REVIEW

**Review by StephanMa — COMMENTED** [review]
lgtm

**Comment by n1tr0-5urf3r** [comment]
No it is the full name of the guild for the search, I guess they're unique? 
Referred to this endpoint: https://wiki.guildwars2.com/wiki/API:2/guild/search

**Comment by StephanMa** [comment]
Would really appreciate it to have this working pr merged..

**Comment by Maselkov** [comment]
Currently looking through it, will test before merging

**Review by Maselkov — CHANGES_REQUESTED** [review]
A few things:
* There's a way to handle arguments with spaces in them without having to use quotation marks - look at character info for example. It looks nicer that way
* Function name "id" conflicts with default python function. This is easy to fix though, add (name="id") to @guild.command (there are examples of this in the code already)
* Member list in an embed is potentially dangerous, if the guild is big. 
* Color might as well use user color, unless you're aiming for something.

**Comment by n1tr0-5urf3r** [comment]
I wrote the Changes requested, 

- Added * and :str, so Guildnames may be invoked without quotation marks
- Added name="id" and renamed id to _id, so it won't conflict with default python function
- Added a counter to the member function, so only the first 51 (actually 51 because it is divisible by 3 for inline embed)
- Changed color to user.colour

Any further requested changes?

**Comment by Maselkov** [comment]
Embed can have a maximum of 25 fields. Maybe return only the few highest rank members? Up to you, but that's a limit. Long embeds don't look nice either.

Also, please use the new getColor(user) method recently added - though your branch isnt up to date
```
    color = self.getColor(user)
    data = discord.Embed(colour=color)
```

Look at code for some examples

**Comment by n1tr0-5urf3r** [comment]
Updated my branch and replaced my color functions with getColor 
For now I think it's best to just display the first 25 Members of the guild, maybe we can change it later to be sorted by ranks. Could be different because guilds name their ranks different

**Comment by Maselkov** [comment]
What about guild/:id/ranks endpoint? The "order" seems to be the same as in game, as in higher order rank has power over lower order ranks

**Comment by n1tr0-5urf3r** [comment]
For now I got order and rank assigned to its member 
Any idea how to store it properly and sort it by order? Im overcomplicating it at the moment

**Comment by Maselkov** [comment]
For example, try to get 11 members from order: 1, and if you dont get 11, get from order 2 and so on until you reach 11. Could use a while loop.

If that's what you mean

**Comment by n1tr0-5urf3r** [comment]
I want to save all members in a list? array? dict? 
So that it looks like 
order1 member1 rank1
order2 member2 rank2

afterwards i can sort by order and print the first X members, but I cant figure out, how to store the data probably, tried it already with a dictionnary
Also with this method I don't have to check how much ranks exists

**Comment by Maselkov** [comment]
Keep in mind dictionaries in python are unordered. You can use a list of dictionaries however
```
[
{Order: 1, Name: "Something", Rank: "Leader"}
{Order: 2, Name: "Whatever", Rank: "Officer"}
]
```
Lists are ordered though. But I'm not exactly sure what you want

**Comment by n1tr0-5urf3r** [comment]
I finally got it working now, not as I intended to do, but it works 
Going through every order in ranks
  For every order the guild has, look up the members and add the associated member to embed
  increment order_id +1
  repeat

Is it fine now?

**Comment by Maselkov** [comment]
Just testing it right now, everything seems fine. But I can't really test bigger guilds yet.

**Review by Maselkov — APPROVED** [review]

**Pull request merged**
