### PR TITLE
Added language parameter

### PR DESCRIPTION
**Pull request by n1tr0-5urf3r**
Added command !langset to save the parameter (en, de, fr, es, ko, zh) for each server in language.json
Added method getlanguage to get language for each server from json
Added language parameter to api call in !guild treasury, get_stat_name, get_title and get_item_name (used in !character gear and info)
langset is not available in direct messages (no server available)
if no language is set, it defaults to english

### CODE REVIEW

**Comment by Maselkov** [comment]
Merge into production without testing, I live dangerously. Can't really test it at the moment.

**Comment by n1tr0-5urf3r** [comment]
I hope I didn't mess up everything^^ but it worked for me 
Can you test it later?

----- Originale Nachricht -----
Von: Maselkov <notifications@github.com>
Gesendet: 03/04/2017 - 20:35
An: Maselkov/Maselkov-Cogs <Maselkov-Cogs@noreply.github.com>
Betreff: Re: [Maselkov/Maselkov-Cogs] Added language parameter (#29)

**Comment by Maselkov** [comment]
Character gear was throwing out json decode errors the first time I tried, but then for some reason it stopped and worked just fine with different languages. Weird.

**Comment by n1tr0-5urf3r** [comment]
I had the same issue, also the guild treasury command threw an „Unknown API Error“ and after some more tries everything worked as expected without changing anything

 

Von: Maselkov [mailto:notifications@github.com] 
Gesendet: Montag, 3. April 2017 22:45
An: Maselkov/Maselkov-Cogs <Maselkov-Cogs@noreply.github.com>
Cc: n1tr0-5urf3r <fabi@ihlecloud.de>; Author <author@noreply.github.com>
Betreff: Re: [Maselkov/Maselkov-Cogs] Added language parameter (#29)

 

Character gear was throwing out json decode errors the first time I tried, but then for some reason it stopped and worked just fine with different languages. Weird.

**Pull request merged**
